import type { Metadata } from "next";

import "./globals.css";
import "./reset.css";
import { Josefin_Sans, Karla, Exo_2 } from "next/font/google";

const josefinSans = Josefin_Sans({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-josefin",
});
const exo2 = Exo_2({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-exo2",
});
const karla = Karla({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-karla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${josefinSans.variable} ${exo2.variable}   ${karla.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
